SELECT INTE.INT_CODIGO, 
       USU.USU_NOME, 
       INTE.INT_DTHCADASTRO, 
       INS.INS_DESCRICAO
FROM INT_INTERESSES INTE
     INNER JOIN USU_USUARIOS USU ON INTE.USU_CODIGO = USU.USU_CODIGO
     INNER JOIN INS_INTERESSESTATUS INS ON INTE.INS_CODIGO = INS.INS_CODIGO
     INNER JOIN ANU_ANUNCIOS ANU ON INTE.ANU_CODIGO = ANU.ANU_CODIGO
WHERE ANU.ANU_CODIGO = @IdAnuncio