SELECT P.PET_NOME, 
       PTS.PTS_DESCRICAO, 
       PID.PID_DESCRICAO, 
       E.EST_SIGLA, 
       C.CID_NOME, 
       F.ANF_LINK, 
       ANT.ANT_DESCRICAO, 
       A.ANU_CODIGO
FROM ANU_ANUNCIOS A
     INNER JOIN PET_PETS P ON A.PET_CODIGO = P.PET_CODIGO
     INNER JOIN EST_ESTADOS E ON A.EST_CODIGO = E.EST_CODIGO
     INNER JOIN CID_CIDADES C ON C.CID_CODIGO = A.CID_CODIGO
     LEFT JOIN ANF_ANUNCIOFOTOS F ON F.ANU_CODIGO = A.ANU_CODIGO
                                     AND F.ANF_DESTAQUE = 1
     INNER JOIN ANT_ANUNCIOTIPO ANT ON ANT.ANT_CODIGO = A.ANT_CODIGO
	 LEFT JOIN PTS_PETSEXOS PTS ON PTS.PTS_CODIGO = P.PTS_CODIGO
	 LEFT JOIN PID_PETIDADES PID ON PID.PID_CODIGO = P.PID_CODIGO
WHERE 1 = 1