SELECT TOP 4 P.PET_NOME, 
             P.PTS_CODIGO, 
             P.PID_CODIGO, 
             E.EST_SIGLA, 
             C.CID_NOME, 
             F.ANF_LINK
FROM ANU_ANUNCIOS A
     INNER JOIN PET_PETS P ON A.PET_CODIGO = P.PET_CODIGO
	 INNER JOIN EST_ESTADOS E ON A.EST_CODIGO = E.EST_CODIGO
	 INNER JOIN CID_CIDADES C ON C.CID_CODIGO = A.CID_CODIGO
     LEFT JOIN ANF_ANUNCIOFOTOS F ON F.ANU_CODIGO = A.ANU_CODIGO
                                     AND F.ANF_DESTAQUE = 1
ORDER BY A.ANU_DTHCADASTRO