SELECT A.ANU_CODIGO, 
       U.USU_NOME,
       ANI.ANI_NOME, 
       ANT.ANT_DESCRICAO, 
       A.ANU_DTHCADASTRO
FROM ANU_ANUNCIOS A
     INNER JOIN PET_PETS P ON A.PET_CODIGO = P.PET_CODIGO
     INNER JOIN ANI_ANIMAIS ANI ON P.ANI_CODIGO = ANI.ANI_CODIGO
     INNER JOIN ANT_ANUNCIOTIPO ANT ON ANT.ANT_CODIGO = A.ANT_CODIGO
	 INNER JOIN USU_USUARIOS U ON U.USU_CODIGO = A.USU_CODIGO
WHERE A.ANS_CODIGO = 1