SELECT A.ANU_CODIGO, 
       P.PET_NOME, 
       ANI.ANI_NOME, 
       A.ANU_DTHCADASTRO, 
       ANS.ANS_DESCRICAO,
(
    SELECT COUNT(*)
    FROM AVI_ANUNCIOSVISITAS
    WHERE ANU_CODIGO = A.ANU_CODIGO
) AS VISUALIZACOES, 
(
    SELECT COUNT(*)
    FROM INT_INTERESSES
    WHERE ANU_CODIGO = A.ANU_CODIGO
) AS INTERESSADOS
FROM ANU_ANUNCIOS A
     INNER JOIN PET_PETS P ON A.PET_CODIGO = P.PET_CODIGO
     INNER JOIN ANI_ANIMAIS ANI ON P.ANI_CODIGO = ANI.ANI_CODIGO
     INNER JOIN ANS_ANUNCIOSTATUS ANS ON ANS.ANS_CODIGO = A.ANS_CODIGO
	 INNER JOIN USU_USUARIOS U ON A.USU_CODIGO = U.USU_CODIGO
WHERE U.USU_CODIGO = @IdUsuario