SELECT USU.USU_CODIGO, 
       USU.USU_NOME, 
       USU.USU_SOBRENOME, 
       USU.USU_DTHNASCIMENTO, 
       USU.USU_SEXO, 
       USU.USU_DOCUMENTO, 
       LOGINS.LOG_EMAIL, 
       LOGINS.LOG_SENHA
FROM USU_USUARIOS USU
     INNER JOIN LOG_LOGINS LOGINS ON USU.LOG_CODIGO = LOGINS.LOG_CODIGO
WHERE USU.USU_CODIGO = @IdUsuario