//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSaver.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetSaver.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0014)about:internet --&gt;
        ///&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;confirmar alteracao de status.png&lt;/title&gt;
        ///&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=utf-8&apos; /&gt;
        ///&lt;style type=&apos;text/css&apos;&gt;td img {display: block;}&lt;/style&gt;
        ///&lt;!--Fireworks CS6 Dreamweaver CS6 target.  Created Mon Dec 10 23:52:22 GMT-0200 2018--&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&apos;text-align: center&apos;&gt;
        ///&lt;table style=&apos;display: inline-table;&apos; bgcolor=&apos;#c6acce&apos; border=&apos;0&apos; cellpadding=&apos;0&apos; ce [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailAlteracaoStatusAnuncio {
            get {
                return ResourceManager.GetString("EmailAlteracaoStatusAnuncio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0014)about:internet --&gt;
        ///&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;title&gt;anuncio aprovado.png&lt;/title&gt;
        ///  &lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=utf-8&apos; /&gt;
        ///  &lt;style type=&apos;text/css&apos;&gt;
        ///    td img {
        ///      display: block;
        ///    }
        ///  &lt;/style&gt;
        ///  &lt;!--Fireworks CS6 Dreamweaver CS6 target.  Created Mon Dec 10 23:08:50 GMT-0200 2018--&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;text-align: center&quot;&gt;
        ///  &lt;table style=&apos;display: inline-table;&apos; bgcolor=&apos;#c6acce&apos; bord [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailAnuncioAprovado {
            get {
                return ResourceManager.GetString("EmailAnuncioAprovado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0014)about:internet --&gt;
        ///&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;cadastro.png&lt;/title&gt;
        ///&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=utf-8&apos; /&gt;
        ///&lt;style type=&apos;text/css&apos;&gt;td img {display: block;}&lt;/style&gt;
        ///&lt;!--Fireworks CS6 Dreamweaver CS6 target.  Created Mon Dec 10 23:42:14 GMT-0200 2018--&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;text-align: center&quot;&gt;
        ///&lt;table style=&apos;display: inline-table;&apos; bgcolor=&apos;#c6acce&apos; border=&apos;0&apos; cellpadding=&apos;0&apos; cellspacing=&apos;0&apos; width=&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailCadastroUsuarioAprovado {
            get {
                return ResourceManager.GetString("EmailCadastroUsuarioAprovado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0014)about:internet --&gt;
        ///&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;confirmar interesse.png&lt;/title&gt;
        ///&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=utf-8&apos; /&gt;
        ///&lt;style type=&apos;text/css&apos;&gt;td img {display: block;}&lt;/style&gt;
        ///&lt;!--Fireworks CS6 Dreamweaver CS6 target.  Created Mon Dec 10 23:56:22 GMT-0200 2018--&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&apos;text-align: center&apos;&gt;
        ///&lt;table style=&apos;display: inline-table;&apos; bgcolor=&apos;#c6acce&apos; border=&apos;0&apos; cellpadding=&apos;0&apos; cellspacing= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailInteresseDemonstrado {
            get {
                return ResourceManager.GetString("EmailInteresseDemonstrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0014)about:internet --&gt;
        ///&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;interesse recebido.png&lt;/title&gt;
        ///&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=utf-8&apos; /&gt;
        ///&lt;style type=&apos;text/css&apos;&gt;td img {display: block;}&lt;/style&gt;
        ///&lt;!--Fireworks CS6 Dreamweaver CS6 target.  Created Tue Dec 11 00:06:08 GMT-0200 2018--&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&apos;text-align: center&apos;&gt;
        ///&lt;table style=&apos;display: inline-table;&apos; bgcolor=&apos;#c6acce&apos; border=&apos;0&apos; cellpadding=&apos;0&apos; cellspacing=&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailInteresseRecebido {
            get {
                return ResourceManager.GetString("EmailInteresseRecebido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0014)about:internet --&gt;
        ///&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;confirmar remocao de interesse.png&lt;/title&gt;
        ///&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=utf-8&apos; /&gt;
        ///&lt;style type=&apos;text/css&apos;&gt;td img {display: block;}&lt;/style&gt;
        ///&lt;!--Fireworks CS6 Dreamweaver CS6 target.  Created Tue Dec 11 00:02:07 GMT-0200 2018--&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&apos;text-align: center&apos;&gt;
        ///&lt;table style=&apos;display: inline-table;&apos; bgcolor=&apos;#c6acce&apos; border=&apos;0&apos; cellpadding=&apos;0&apos; c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailInteresseRemovido {
            get {
                return ResourceManager.GetString("EmailInteresseRemovido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0014)about:internet --&gt;
        ///&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;pergunta recebida.png&lt;/title&gt;
        ///&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=utf-8&apos; /&gt;
        ///&lt;style type=&apos;text/css&apos;&gt;td img {display: block;}&lt;/style&gt;
        ///&lt;!--Fireworks CS6 Dreamweaver CS6 target.  Created Tue Dec 11 00:10:01 GMT-0200 2018--&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&apos;text-align: center&apos;&gt;
        ///&lt;table style=&apos;display: inline-table;&apos; bgcolor=&apos;#c6acce&apos; border=&apos;0&apos; cellpadding=&apos;0&apos; cellspacing=&apos;0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailPerguntaRecebida {
            get {
                return ResourceManager.GetString("EmailPerguntaRecebida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;
        ///&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;!-- saved from url=(0014)about:internet --&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;title&gt;resposta recebida.png&lt;/title&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///  &lt;style type=&quot;text/css&quot;&gt;
        ///    td img {
        ///      display: block;
        ///    }
        ///  &lt;/style&gt;
        ///  &lt;!--Fireworks CS6 Dreamweaver CS6 target.  Created Tue Dec 11 00:13:02 GMT-0200 2018--&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailPerguntaRespondida {
            get {
                return ResourceManager.GetString("EmailPerguntaRespondida", resourceCulture);
            }
        }
    }
}
